### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by sadortun** [orocrm/oro-phpstorm-plugin#1]
Hi @psliwa ,

It would be nice if you could add more details in the readme and in the plugin description
![image](https://cloud.githubusercontent.com/assets/794449/14764021/aaf4928e-0976-11e6-9c6d-d4200087792e.png)

if you look at the Symfony2 plugin there is more than 10 examples of what the plugin provides.

Thanks,
Samuel

**Comment by psliwa** [comment]
Hi, thanks for the very first issue and sorry for late respond :)

The plugin is under heavy development right now and the first stable version is not yet ready. The features list will be provided when the stable release is close enough. In nullshell, right now the plugin covers support for acl.yml, entity.yml and datagrid.yml files.

**Comment by sadortun** [comment]
Hi @psliwa 

Great, can you list what is supposed to work, and what will be relased in a later version ? Screen captures would be great also !

Have a good day,
Samuel

**Comment by psliwa** [comment]
As I said, right now autocompletion and basic inspections for `acl.yml`, `entity.yml` (basic one, not full support), `datagrid.yml` (basic support, without advanced stuff as DQL completion etc) is ready. In next weeks you can expect support for e.g. `workspace.yml`.

Screen captures and other documentation will be done when the plugin covers more features and is much more close to be stable. Right now even the plugin is not released to PhpStorm plugin's repository.

**Comment by iklymenko** [comment]
@sadortun, added list of the features to the README.md. We will update it with new features regularly.
Another way is to read release notes: https://github.com/orocrm/oro-phpstorm-plugin/releases

**Comment by sadortun** [comment]
Great!
