### ISSUE TITLE
NOTE: PhpTypeProvider3.getBySignature method signature change in next EAP

### ISSUE THREAD

**Issue by neuro159** [orocrm/oro-phpstorm-plugin#10]
/**
   * @param expression Signature expression to decode. You can use PhpIndex.getBySignature() to look up expression internals.
   * @param visited Recursion guard: please pass this on into any phpIndex calls having same parameter
   * @param depth Recursion guard: please pass this on into any phpIndex calls having same parameter
   * @param project well so you can reach the PhpIndex  @return null if no match
   */
  Collection<? extends PhpNamedElement> getBySignature(String expression, Set<String> visited, int depth, Project project);

**Comment by Haehnchen** [comment]
@neuro159 please think about changing a method signature of an interface which is already out in the wild. As i see `PhpTypeProvider3` is provided in `PhpStorm 2016.2.1` as `getBySignature(String paramString, Project paramProject)`. Simply a plugin is not able to provide support for both api's then without maintaining 2 versions or explicitly disallow plugin installation for all PhpStorm builds which use the old signature.

related: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/792

**Comment by neuro159** [comment]
This is the only usage out of our own codebase (that is in a plugin uploaded to plugin site). Actually I was surprised that you already using it as it is not finalised/documented at http://confluence.jetbrains.com/display/PhpStorm/PHP+Open+API

Anyway, PhpTypeProvider3 was added specifically to allow me to re-do stuff not handled properly in PhpTypeProvider2 and PhpTypeProvider(1). Its NOT final yet and expected to change until release of 2016.3.

We're now working actively better PHP open API (more sources, docs, internal utils open). I'm always available for comment (eg via Skype), ping me if you discover something fresh and shiny before using it)

**Comment by Haehnchen** [comment]
right now its the "only usage". But if you deprecate the old one in your code we will search for the alternatives. at that point we got the knowing about this new implementation. :)

i am with you: ´PhpTypeProvider´ is a "lessons learned" implementation, all improvements are welcome.

**Comment by psliwa** [comment]
@neuro159 Thanks for letting know, I've fixed its implementation in the codebase and released new version.

@Haehnchen There is a way to support both `PhpTypeProvider3.getBySignature` versions, just implement two `getBySignature` methods, one of the methods mustn't have `@Override` annotation - it is a hack, but it allows to support all 2016.* versions of PhpStorm on one codebase.
