### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Desmaster** [orocrm/oro-phpstorm-plugin#2]
Would be kind of nice to have a __Installation__ heading in the README. Currently only people who have created phpstorm plugins, know how to install it :).

**Comment by iklymenko** [comment]
@Desmaster, I'm happy to announce that we published [Oro PHPStorm Plugin to the official JetBrains repository](https://plugins.jetbrains.com/plugin/8449), so developers are able to install and upgrade it in the regular way as other plugins.

**Comment by Desmaster** [comment]
Great to hear! Guess it only needs to be mentioned in the readme then. :)

**Comment by iklymenko** [comment]
@Desmaster, [done](https://github.com/orocrm/oro-phpstorm-plugin/blob/master/README.md#install-and-upgrade)
