### ISSUE TITLE
API Routes not listed

### ISSUE THREAD

**Issue by sadortun** [orocrm/oro-phpstorm-plugin#6]
Hello Piotr !

It would be a nice addition if the plugin could provide hint for API routes. 

![image](https://cloud.githubusercontent.com/assets/794449/17268520/786cac72-55fa-11e6-9096-1f6e9ee89900.png)

Have a good day,
Samuel

**Comment by vsoroka** [comment]
Hello @sadortun,

The Symfony plugin for PhpStorm has the feature you need. I've tested it in my PhpStorm and it works fine. Why do you think that we need to implement it in our plugin?

**Comment by sadortun** [comment]
Great ! It's working on the last version ! 
![image](https://cloud.githubusercontent.com/assets/794449/17739211/553b38b0-6462-11e6-88ae-68554fbf5c9e.png)
