### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by diglin** [orocrm/oro-phpstorm-plugin#7]
The plugin cannot be found through the plugin interface of PHPStorm, so I tried to install it manually by downloading the zip file. However, trying to install the plugin, I got following errors:

I downloaded the 1.0.0-alpha15

![capture d ecran 2016-08-31 a 12 35 38](https://cloud.githubusercontent.com/assets/1337461/18125611/7a83e4c6-6f77-11e6-881c-99519fc8bbee.png)

I use PHPStorm 2016

![capture d ecran 2016-08-31 a 12 36 22](https://cloud.githubusercontent.com/assets/1337461/18125621/8a803bfe-6f77-11e6-9ac4-124bafc33977.png)

**Comment by mbessolov** [comment]
@diglin plugin requires PHPStorm 2016.1+
